Plugin:
  Prefix: 'Economy'
  Command_Aliases: 'sleconomy,sleco'
  Language: 'en'

Database:
  Type: SQLite
  Auto_Save_Interval: 15
  Sync_Interval: 30
  Table_Prefix: 'sunlight_economy'
  MySQL:
    Username: 'user'
    Password: '123'
    Host: 'localhost:3306'
    Database: 'server'
  Purge:
    Enabled: false
    For_Inactive_Days: 60

BalanceTop_Update_Interval: 15
Currency:
  Name:
    Singular: '$'
    Plural: '$'
    Format: '%name%%amount%'
  Start_Balance: 100.0
