Title: '#5d6d7e           &lHome Settings'
Size: 45

Content:
  return:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmU5YWU3YTRiZTY1ZmNiYWVlNjUxODEzODlhMmY3ZDQ3ZTJlMzI2ZGI1OWVhM2ViNzg5YTkyYzg1ZWE0NiJ9fX0='
      Name: '#e3fbf9(↓) &lReturn'
    Slots: 40
    Type: RETURN

  location:
    Item:
      Material: COMPASS
      Name: '#ee9aff&lLocation'
      Lore:
        - '#ee9aff▪ #ddeceeWorld: #ee9aff%home_location_world%'
        - '#ee9aff▪ #ddeceeX: #ee9aff%home_location_x%'
        - '#ee9aff▪ #ddeceeY: #ee9aff%home_location_y%'
        - '#ee9aff▪ #ddeceeZ: #ee9aff%home_location_z%'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffSet to current'
    Slots: 4
    Type: HOME_CHANGE_LOCATION

  def:
    Item:
      Material: GREEN_BED
      Name: '#ee9aff&lDefault Home'
      Lore:
        - '#ee9aff▪ #ddeceeEnabled: #ee9aff%home_is_default%'
        - ''
        - '#ddeceeWhen enabled, teleports you to this home'
        - '#ddeceeif you don''t specify other home name.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffToggle'
    Slots: 19
    Type: HOME_CHANGE_DEFAULT

  respawn:
    Item:
      Material: RED_BED
      Name: '#ee9aff&lRespawn on Death'
      Lore:
        - '#ee9aff▪ #ddeceeEnabled: #ee9aff%home_is_respawn_point%'
        - ''
        - '#ddeceeWhen enabled, teleports you to this home'
        - '#ddeceeon after death respawn.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffToggle'
    Slots: 20
    Type: HOME_CHANGE_RESPAWN_POINT

  name:
    Item:
      Material: NAME_TAG
      Name: '#ee9aff&lDisplay Name'
      Lore:
        - '#ee9aff▪ #ddeceeCurrent: #ee9aff%home_name%'
        - ''
        - '#ddeceeSets the home display name.'
        - '#ddeceeIt will be displayed in menus and messages.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange'
    Slots: 21
    Type: HOME_CHANGE_NAME

  public:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2I1NmU0OTA4NWY1NWQ1ZGUyMTVhZmQyNmZjNGYxYWZlOWMzNDMxM2VmZjk4ZTNlNTgyNDVkZWYwNmU1ODU4YyJ9fX0='
      Name: '#ee9aff&lHome Type'
      Lore:
        - '#ee9aff▪ #ddeceeCurrent: #ee9aff%home_type%'
        - ''
        - '#ddeceePublic home allows anyone to visit it.'
        - '#ddeceePrivate home is accessible by invites only.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffToggle'
    Slots: 22
    Type: HOME_CHANGE_TYPE

  icon:
    Item:
      Material: ITEM_FRAME
      Name: '#ee9aff&lIcon'
      Lore:
        - '#ddeceeSets the home icon to be displayed in GUI.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeDrag & Drop: #9af7ffChange'
    Slots: 23
    Type: HOME_CHANGE_ICON

  invites:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTc5ZTkxMTczY2U1NzhlMWI1NWYyMGYxMTk2NjE3NDI5ZWE2ODhlNjczNDVkN2ZmYmNmNWFhZWRkNjViZjU5OSJ9fX0='
      Name: '#ee9aff&lInvited Players'
      Lore:
        - '#ee9aff▪ #ddeceeInvited: #ee9aff%home_invited_players%'
        - ''
        - '#ddeceeA list of players, who can visit'
        - '#ddeceeyour home at any time.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffAdd Player'
        - '#9af7ff▪ #ddeceeRight-Click: #9af7ffClear List'
    Slots: 24
    Type: HOME_CHANGE_INVITED_PLAYERS